package:
  format-version: "1.0.0"
  name: "net_apps_sama7d6"
  type: "application"
  status: "production"
  required: false
  version: "v1.0.0"

  dependencies:
    - name: "net"
      type: "package"
      version: "v3.12.3"
    - name: "core"
      type: "package"
      version: "v3.13.5"
    - name: "csp"
      type: "package"
      version: "v3.19.6"
    - name: "bsp"
      type: "package"
      version: "v3.20.1"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"